### ISSUE TITLE
Add call recording (video)

### ISSUE THREAD

**Issue by allerpi** [ac-datamatics/ccp-embed#11]
- [x] Start recording when call is answered
- [x] Stop recording when after-call work is done (onDestroy)
- [x] Upload on S3

**Comment by edvilme** [comment]
See https://github.com/ac-datamatics/web/blob/screen-recording-rtc/RecorderRTC/recorder.js
- [x] Convert to class with `start()`, `stop()`and `onDataAvailable(callback)` methods
- [x] Integrate with `CCP` event listeners
